### ISSUE TITLE
Returning Loan item with Stock items on Loan qty error

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#104]
If a Loan includes Loan and Stock items, on check-in of the loan item an error will appear for the stock items that are not returned. "Qty cannot be negative"

![stock item error1](https://user-images.githubusercontent.com/76882506/114548597-e26fd600-9c57-11eb-8e43-f59a7a35d96d.png)
![stock item error2](https://user-images.githubusercontent.com/76882506/114548600-e3086c80-9c57-11eb-999c-60d0b9bc25b1.png)

**Comment by andortamas** [comment]
Bugfix is available in fix_104 branch

**Comment by chris-b-tanner** [comment]
@LESupport could you work with Andor on this to QA and then promote to production?

**Comment by LESupport** [comment]
Complete https://gitlab.com/chris-tanner/lend-engine-app/-/issues/104
