### ISSUE TITLE
Custom opening hours stopped being active

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#108]
Had a call raised about the custom opening hours of a site no longer in effect, I tested my own, mine too were no longer active. 

deleted them and re-creating them solved the immediate issue, but I'm unsure what stopped them from being active.
![custom opening hours](https://user-images.githubusercontent.com/76882506/115861877-49954380-a42b-11eb-8bc6-3128562c22fb.png)
![Screenshot 2021-04-23 at 12 41 32](https://user-images.githubusercontent.com/76882506/115864261-8adb2280-a42e-11eb-82d2-402adcb7ccc8.png)
![Screenshot 2021-04-23 at 12 43 57](https://user-images.githubusercontent.com/76882506/115864306-94648a80-a42e-11eb-9a61-b949e3da0f77.png)

**Comment by andortamas** [comment]
@LESupport I have tested on my local machine, but I couldn't replicate the issue. Can you explain more how I can reproduce this issue please?

**Comment by LESupport** [comment]
> @LESupport I have tested on my local machine, but I couldn't replicate the issue. Can you explain more how I can reproduce this issue please?

Hi, I'm not sure how we would go about re-creating the problem, I created the custom hours to close our site and checked that they had taken effect (tried to book something out for this period), and all looked good. Went back in about a month later and they were no longer active, no changes to the hours had happened during that period. I'm not sure how we would recreate that, could it be down to a release?

**Comment by andortamas** [comment]
@LESupport: I have tried locally to close the main site with adding custom hours and systems ignored it. I can see the in the list that the site should be closed, but I could borrow and reserve items. Is this normal?

**Comment by LESupport** [comment]
> @LESupport: I have tried locally to close the main site with adding custom hours and systems ignored it. I can see the in the list that the site should be closed, but I could borrow and reserve items. Is this normal?

 It should close the site, I've added temp closure on the demo site for North HQ on 28th April and it worked, if you try to book something out from that location on that date you will see its closed. here are some screenshots from my site showing it as closed on the 3,4 Aug.

![normal opening hours](https://user-images.githubusercontent.com/76882506/116143669-53d96b00-a6d3-11eb-84c7-8d510901cd21.PNG)
![closed custom hours](https://user-images.githubusercontent.com/76882506/116143673-55a32e80-a6d3-11eb-9c67-66897aa00bfa.PNG)
![closed 3rd and 4th Aug](https://user-images.githubusercontent.com/76882506/116143680-58058880-a6d3-11eb-8880-e50fdf8ffd54.PNG)

**Comment by andortamas** [comment]
Great. I checked on my local environment and it works here as well, but only for full days.

For example: if I close the site from 07am to 14pm, I can borrow an item, see the screenshots.

![Screenshot 2021-05-03 at 12 13 41](https://user-images.githubusercontent.com/1197217/116865107-49562e80-ac09-11eb-8827-2aa9120e68f0.png)
![Screenshot 2021-05-03 at 12 14 16](https://user-images.githubusercontent.com/1197217/116865120-4ce9b580-ac09-11eb-9e27-d760796f767d.png)
