### ISSUE TITLE
Update language Slovenščina

### ISSUE THREAD

**Issue by chris-b-tanner** [lend-engine/lend-engine-app#109]
The name for the language "Slovenian" needs to be updated to "Slovenščina" : in admin settings and on the member site (when a user views the website, there's a choice in the footer) and when a new user registers they can choose their language.

The language translations have also been updated. @andortamas I will send you login details for our translation platform.
Download the two translation files (emails.yml and membersite.yml) for this language, and overwrite the translation files in Lend Engine code.

**Comment by andortamas** [comment]
All done and ready to UAT on the staging server.

**Comment by LESupport** [comment]
UAT
The language was added to what members can choose from already
Changed default language to Slovene and checked against Loco
Change the language on the home page to Slovene using the option at bottom of the screen and checked translation with Loco
Updated language on User(non-admin) profile to Slovene and checked against Loco
Updated default language back to UK and checked.
Removed Slovene language option and checked homepage, language option has now gone.
