### ISSUE TITLE
Add Catalan language

### ISSUE THREAD

**Issue by chris-b-tanner** [lend-engine/lend-engine-app#110]
@andortamas could you download the Catalan files from Loco and add as a language that users can choose in Lend Engine?
Search for "nl" (or any other already-supported language codes) to see where languages are chosen. @LESupport can you UAT and approve on Staging once done?
Thanks

**Comment by andortamas** [comment]
UAT
- Admin can choose to add Catalan to the list of choices which appear on the member site
- User can choose Catalan when registering for a new account and their website view will show in Catalan
- Change the language on the member site to Catalan and check the translation

Note: our Catalan translation has a 77% coverage, so missing strings are covered from the Spanish translation as a fallback.

**Comment by andortamas** [comment]
Released and available to UAT on the staging server.

**Comment by LESupport** [comment]
UAT test - Issue selecting language as a user in the member's profile
Fail - unable to select Catalan as users language on the member's profile.

Added Catalan in members site as an option for languages
Able to add Catalan for the home screen when not logged in
Select Catalan as the default language and tested the effect on the user 
Able to change back to English as default and see the user change back
checked 5 language changes with Loco and all are in Catalan

![language picker](https://user-images.githubusercontent.com/76882506/116140626-81bcb080-a6cf-11eb-8366-b75258af2de2.png)

**Comment by andortamas** [comment]
Goog spot, thanks for catching this issue. I've fixed this and ready to test on the staging server.

**Comment by LESupport** [comment]
> Goog spot, thanks for catching this issue. I've fixed this and ready to test on the staging server.

Looks good! ready for deployment

**Comment by LESupport** [comment]
Complete, 
https://gitlab.com/chris-tanner/lend-engine-app/-/issues/110
