### ISSUE TITLE
Custom opening hours not functioning 

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#116]
Using custom hours to open a site or close a site for regular hours does not function. The calendar does not show the hours available for days open and does not close the location for days closed using custom hours.

the has been recreated on the Demo site for the location "Central Library" 

- On the day "24th May" the Central Library has been opened using custom hours and it displays none
- On the day "25th May" the Central Library has been opened using an event that allows pickup and drop-offs
- On the day "26th May" the Central Library had normal opening hours and using custom hours the site has been closed

None of the above cases function.

you can use the item "Frog tadpole balance bike" to see the calendar when you browse the calendar on the 24,25,26th May.

Custom hours are added here:-
http://demo.lend-engine.com/admin/site/list

An Event can be added here:-
http://demo.lend-engine.com/admin/event/list

![calendar](https://user-images.githubusercontent.com/76882506/119274212-b6f0eb80-bc06-11eb-8381-5905ee7230be.png)
![custom hours issue](https://user-images.githubusercontent.com/76882506/119274216-ba847280-bc06-11eb-920a-ba5f50541cf1.png)
![event no hours](https://user-images.githubusercontent.com/76882506/119274221-bc4e3600-bc06-11eb-930e-6803cb8f2157.png)

**Comment by andortamas** [comment]
Fixed and ready to UAT

**Comment by LESupport** [comment]
UAT
1. Opened site using custom opening hours and confirmed site was available for booking.
2. Opened site using event with "Pickup and Drop-offs" enabled, confirmed the site was available for booking and made a reservation.
3. Closed Site for the day and confirmed the site was on day

Potential (additional) bug
1. When a site is closed and the open and closed times envelope other sites on that day it closes that site two 
Recreate on Demo site on Wednesdays:-  Town Library is open 0900 to 1800 and the North Campus HQ is open 1400 - 1600 if you close the Town Library from 0900 to 1800 North Campus HQ disappears too.

Notes
1. You cannot close sites for partial days using custom hours when it has regular hours.
2. You can open a site with the from and to times the same and it will allow it, but in the calendar, it will say open from "0900 to Invalid date" see 3rd of September 2021 in demo library
3. You can open a site for 15 mins and it will allow booking.

**Comment by chris-b-tanner** [comment]
Super work guys, thank you!

Chris

**Comment by andortamas** [comment]
Potaential (additional) bug has been fixed and ready to UAT

**Comment by LESupport** [comment]
Looks good to me, let's release this and I'll create tickets for the other small issues, (Note 2)
