### ISSUE TITLE
Setting Minimum Loan Period to 14 days causes problems with item loan periods on catalogue view

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#117]
Loans appear in the catalogue for the wrong period

Steps to reproduce, 
1, Set item to 7-day loan for £10
2. Set the global minimum loan period to 14 days
3. View item in the catalogue 

From Chris
\AppBundle\Controller\MemberSite\Item\minLoanDays
src/AppBundle/Controller/MemberSite/Item/ItemListController.php:214

![loan period problem](https://user-images.githubusercontent.com/76882506/119668413-13365400-be2f-11eb-9438-fd2a41e7f09f.png)

**Comment by andortamas** [comment]
Fix is done and available on the staging server

**Comment by LESupport** [comment]
Changed loan period in global setting to 14 days checked items and they are at the correct value, removed item loan setting and checked they inherit global settings. All looks good.

Booking error 
Booked an item for the full 14 days from global settings, this allows the return on a closed date
Changed setting on the item to 3-day loan, booked item, this also allowed the reservation to book the return on a closed day.
