### ISSUE TITLE
User can extend an loan over existing reservations 

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#120]
If something is checked out and on loan, an extension can be created that extends past an existing reservation.

Steps to recreate:-

First user, Create a reservation for an item and then checkout.
Second user, create an adjacent booking to the above loan
First user, extends loan over second users booking (a day passed)
![book over existing reservation](https://user-images.githubusercontent.com/76882506/120995362-3e00a080-c77d-11eb-807e-b99ef993d237.png)

**Comment by YvetteKlinkenberg** [comment]
This is a major issue as we encourage people to use self service for loan extension.

**Comment by LESupport** [comment]
UAT - Pass
As user created a reservation for an item
As Admin, checkout out the loan
As Admin created a reservation for a different user in an a adjacent time period
As a user tried to extend a loan on or over the existing reservation, the system prevented this with the message "Your selected period clashes with an existing booking. Please choose another date."

**Comment by LESupport** [comment]
Released
