### ISSUE TITLE
As a user you can check-in on an event that is not self serve "book now" is not available

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#123]
User should not be allowed to "check in" or "book now" to an event that is not self serve.

**Comment by andortamas** [comment]
Developing the unit and functional tests are required.

**Comment by LESupport** [comment]
UAT 
Made event with "Allow self serve booking?" set to no. tested that a standard user could not check-in
Changed event to paid with self-check-in now shows "book" only.
Changed event to zero cost, only allows book and no check in available

**Needs to allow check-in and booking on zero cost event**
as per text on event window:-
"Checking in to an event adds an attendee without sending a booking confirmation email. Check in just as though you were booking online. Check in is only possible for free events, or if you are admin browsing on behalf of a user."

**Comment by LESupport** [comment]
UAT - Pass
Created even and made self-serve, as sure was able to check-in and book now
Reached Max attendees and as user was unable to book
As admin was able to check-in user and book as expected.
Made event an admin book only, as a user, unable to book or check-in, but able to do both as admin.

**Comment by andortamas** [comment]
Deployed
