### ISSUE TITLE
Booking item allows return on a closed day

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#127]
Booked an item for the full 14 days loan period from global settings, this suggests the return date on a closed date where regular hours are not used.
Changed loan setting on the item to include 7-day loan, booked item, this also suggests the reservation to book the return on a closed day.

When using custom hours to open a location the loan period should show the return as unavailable and for the user to select another date for the return. for any reason that the return date is not available to perform a return.
![selected to day for 14 day loan not open](https://user-images.githubusercontent.com/76882506/121063479-44633c80-c7be-11eb-9537-5a073caaddb2.png)

**Comment by LESupport** [comment]
As Admin Created custom open day with another 14 days later (19th June and 3rd July both without changeover time)
As user  made a reservation of item with 7 day loan period, this worked as expected offering the user to select a return date
As user  made a reservation of item with 14 day loan period, this worked as expected offering the user the correct return date

Major 
**change to the current system**
Adding more than one item to a loan required you to select the "too date" for every item even when the item is for the same period and the "item loan period is the same" as an existing item in the reservation (this is a new issue)

Booking outside of open hours possible with the second item, the first item did not adhere to the end hours for the day without change over time booked till 1200 but the end of the day was 1500 (see #128 for details)
The second item automatically booked till 1500, but when clicked reserve the reservation shows 1600.
![booking outside of hours possible with two items](https://user-images.githubusercontent.com/76882506/121966857-42255300-cd67-11eb-81c6-08b021d9ea27.png)

**Comment by LESupport** [comment]
UAT - Pass 
Adding more items to the loan offer the correct date for return and requests date is selected if the location closed.
Loans can have items with different return dates

**Comment by andortamas** [comment]
Deployed

**Comment by LESupport** [comment]
Calendar rollover issue in "July" calendar a booking for "Aug" does not comply with opening hours for closed days or custom open days.
![not suggesting next slot on the 12th](https://user-images.githubusercontent.com/76882506/126625412-ea33bdc0-1839-43a8-a11e-c2c85989360a.png)
![offers closed day on 11th Aug from July calendar](https://user-images.githubusercontent.com/76882506/126625502-af337af3-ab5e-42e1-a867-38cab3deb9ec.png)

**Comment by LESupport** [comment]
Released
