### ISSUE TITLE
Loans do not adhere to conditions set out in opening hours and will set to opening time instead of closing time.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#128]
for opening times with no changeover time, the system should adhere to the rule stated in the window 

"If you don't set a changeover time, then loans and reservations run from the start of the pickup slot to the end of the return slot, to maximise loan time and help prevent clashes. To allow same-day return and pickup, loans should be returned at the beginning of a slot. Set your changeover time to the beginning of the day."

![image](https://user-images.githubusercontent.com/76882506/121376808-bc09a680-c939-11eb-94cc-1532fe6e7125.png)

![image](https://user-images.githubusercontent.com/76882506/121377210-1145b800-c93a-11eb-8843-f8fcb8108a1a.png)

![image](https://user-images.githubusercontent.com/76882506/121376176-371e8d00-c939-11eb-8a05-d518acb8b5f3.png)

**Comment by LESupport** [comment]
UAT test
1. Changed opening times of a location to include various days with and without changeover 
2. As the user booked items within days where no changer and the item book as expected from the start of the day to the end of the day this included custom open days.
3. As the user booked multiple items on one loan with the same pickup and drop off location.
4. As admin book items using Calendar and worked as above.
5. Changed item loan period to not match current loan booking and added to an existing loan as expected ask to select too date

Possible issues.
Major (change to the current system)
Adding more than one item to a loan required you to select the "too date" for every item even when the item is for the same period and the "item loan period is the same" as an existing item in the reservation (new issue)

Minor (could create a new issue for this)
As admin used the "Today" button in the calendar selection on reservations then went to select "too date" and this created error "Start time is not within opening hours" and unable to continue, had to cancel to get past this issue.

**Comment by LESupport** [comment]
UAT - PASS

Without changeover time the reservations are set to the end of the day as expected.
With changeover time the reservations are set to the changeover time as expected.

Minor (could create a new issue for this)
As admin used the "Today" button in the calendar selection on reservations then went to select "too date" and this created error "Start time is not within opening hours" and unable to continue, had to cancel to get past this issue.

**Comment by LESupport** [comment]
Retest after "today" button looked at, no longer in loop, but does not appear when it should be possible to use, Andor to look at on Monday.

**Comment by LESupport** [comment]
The issue with "today" button moved to a new problem https://github.com/lend-engine/lend-engine-app/issues/130 to this can be released.

**Comment by andortamas** [comment]
Deployed
