### ISSUE TITLE
maintenance change date & location at once bug

### ISSUE THREAD

**Issue by YvetteKlinkenberg** [lend-engine/lend-engine-app#131]
When I try to select a new date for maintenance via the 'change date' option in the maintaince admin page and change the location of the item at once, I get an "Oops":

![image](https://user-images.githubusercontent.com/17195572/124396978-3b0db700-dd0d-11eb-9d0a-06a5aa927916.png)

**Comment by YvetteKlinkenberg** [comment]
However, it seems that the change of date was saved in the database, but this results in a wrong status:
due date 10th of July, today it's the 4th of July and the status of maintenance is (still) overdue:
![image](https://user-images.githubusercontent.com/17195572/124397043-a5265c00-dd0d-11eb-8492-0feccfb630f6.png)

**Comment by LESupport** [comment]
Thanks, Yvette, I've replicated this on our test system too.

**Comment by LESupport** [comment]
UAT - PASS

Created a number of tasks and manipulated them logic now works as I'd expect.

**Comment by LESupport** [comment]
Released
