### ISSUE TITLE
Start time is not within opening hours issue

### ISSUE THREAD

**Issue by andortamas** [lend-engine/lend-engine-app#134]
Latest release introduced an issue on the validate booking time functions.

![WhatsApp Image 2021-07-07 at 14 03 46](https://user-images.githubusercontent.com/1197217/124965044-fc843f00-e021-11eb-8fdf-3a9b0c13dc20.jpeg)

**Comment by andortamas** [comment]
It's not ready yet, reverted the #127 changes

**Comment by LESupport** [comment]
UAT Pass
Extended loan within opening times without issue

**Comment by LESupport** [comment]
Released to live by Chris on 12/07/21 at 14:00

**Comment by andortamas** [comment]
A bug has been fixed and available for re-testing on the staging server.

**Comment by LESupport** [comment]
While the following booking did present the correct times for pick up drop off using changeover times, the user was able to change the drop off time to outside of opening hours.
![opening times](https://user-images.githubusercontent.com/76882506/127010579-ce98bb13-64fa-433b-b31c-a65bdeec15fb.png)
![can book outside of opening times](https://user-images.githubusercontent.com/76882506/127010620-7e12d93c-27ab-460b-9785-2502fae2a1a1.png)

**Comment by LESupport** [comment]
UAT - Pass
Created custom hours for 7-day loans for a period with changeover and a period without changeover both suggested the right time and was able to modify to reflect any time within opening hours. Also checked regular hours and worked as above.

**Comment by andortamas** [comment]
Deployed.
