### ISSUE TITLE
Card payment system fails to submit after any error occurs 

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#135]
If an error for missing information or incorrect details is detected the submit button fails to respond.

Recreate this issue on a test system
as a user try to submit the following information for payment of membership or item
test card number 4242 4242 4242 4242 exp 01/24 ccv 999 (omit Zip) and press "add credit"
an error will appear "Zip incorrect" 
if you follow up with the correct information such as test card number above with zip 99999 and click "Add credit" nothing happens. "Process form" fails with no error thrown.

The same happens for a card failure with test info 4000 0000 0000 0010 exp 01/24 ccv 999 zip 99999 "Fails postcode verification"

The workaround is to reload the page
![payment failure](https://user-images.githubusercontent.com/76882506/125269693-da7c0c80-e300-11eb-9e80-d5e1bbf3742f.png)

**Comment by andortamas** [comment]
Deployd.
