### ISSUE TITLE
When reservation is made using custom opening hours it allows return on closed days

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#136]
When using custom opening hours, if the loan is for 14 days and there is no open time at that location on that day of return it will still populate the loan return and allow the loan to be created
![custom hours loan creation](https://user-images.githubusercontent.com/76882506/125295230-ed9cd580-e31c-11eb-9eda-605f96b34660.png)

**Comment by andortamas** [comment]
The calendar times are refactored in the #134, #137 and #138 issues which also fixed this one as well.

**Comment by LESupport** [comment]
UAT 

(new issue) When creating a reservation for North campus (HQ) that opens at 0900 and closes at 1500 the model showed the correct time, but the reservation shows pickup from 0600 and return at 1200, it should say pickup at 0900 and return at 1500 as there is no change over time at North campus (HQ)
![modal has correct times then changes on reservation](https://user-images.githubusercontent.com/76882506/128687764-d4232c7b-d848-40c8-81db-d76c146e1c5a.png)

![reservation shows 9am on calendar basket and booking shows 6am](https://user-images.githubusercontent.com/76882506/128685048-70ab9b03-99f6-4200-9ee4-ccdfb06d2ff0.png)

(existing issue) When adding a second loan item to an existing reservation with a location with changeover the pickup time is displayed correctly in the modal, but the reservation for the second item change to 0800 instead of 0700
![add loan item to existing booking](https://user-images.githubusercontent.com/76882506/128687856-e90d915e-a33f-4572-8ec6-70e350f4350c.png)

![not correct time for existing reservation](https://user-images.githubusercontent.com/76882506/128686189-61ee0028-f996-4967-bbc4-ab0397dfc2d9.png)

(existing issue) Adding another item to an existing reservation with a location without a changeover time, the modal shows the correct dates and times, but the reservation jumps forward an hour which is outside of the opening hours.
![adding another loan item modal](https://user-images.githubusercontent.com/76882506/128688699-cda224a7-3b2f-4fdd-a09a-e69fd3467f24.png)
![adding another loan item](https://user-images.githubusercontent.com/76882506/128688709-d4869572-ddfd-4243-9726-4bf89aa55265.png)

**Comment by andortamas** [comment]
These issues not relating to the current bugfix, so raised the #140 to fix them.

**Comment by LESupport** [comment]
UAT - Pass
Created multiple reservations on days that are closed for custom hours and normal hours, now prevents dates being offered on closed days

**Comment by andortamas** [comment]
Deployed.
