### ISSUE TITLE
Cannot auto-set end date as there is no opening hour slot for T+4

### ISSUE THREAD

**Issue by andortamas** [lend-engine/lend-engine-app#137]
When you select a date to pick up, the modal would set the return date automatically. It has a bug on setPickup function which thinks the return date is not available.

![Screenshot 2021-07-26 at 14 25 26](https://user-images.githubusercontent.com/1197217/126989043-d28420c9-241c-4098-a49e-3697915047f6.png)
![Screenshot 2021-07-26 at 14 25 38](https://user-images.githubusercontent.com/1197217/126989049-41b6b004-527b-4bc9-9ec6-5a2606d424b3.png)

**Comment by LESupport** [comment]
When adding a second loan item the modal auto picks the start date but not the return date (both items were 7 days loans)
![adding second loan item to existing loan modal does not auto select return date](https://user-images.githubusercontent.com/76882506/127004930-8b7af809-8736-42b1-b555-13a6cf5b0e4b.png)

**Comment by andortamas** [comment]
Looks good now.

**Comment by LESupport** [comment]
UAT- Pass 

Custom and standard opening hours work as expected, created custom hours and reservation does auto-populate the return as expected when the hour's match for both the primary item and any additional items.

**Comment by andortamas** [comment]
Deployed.
