### ISSUE TITLE
Calendar allowed returning date despite the site is closed

### ISSUE THREAD

**Issue by andortamas** [lend-engine/lend-engine-app#138]
There are some calendar view anomalies, the site is closed on the 11th Aug for North Campus, If I make a booking in the "July" view of the calendar to start on the 5th Aug it will allow the return on the 11th Aug (the closed day), if I move forward to the August calendar it won't allow the booking.

![calendar-anomalies](https://user-images.githubusercontent.com/1197217/127016244-a5d6a299-45ed-40c9-aa1f-24e5d3a09182.jpeg)

**Comment by LESupport** [comment]
UAT - PASS
Checked both dates on the overlapping calendar and they work as expected.
