### ISSUE TITLE
Search box does not return results for multiple words

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#139]
Words need to be consecutive to function

i.e "Petrol blower" brings back nothing
http://demo.lend-engine.com/products?search=Petrol+blower
"Leaf Blower" will work
http://demo.lend-engine.com/products?search=leaf+blower

Need the search to take into account the item name and keywords in any order to be useful in both the member's site and the admin "Item search"
Jalen raised this issue.

**Comment by LESupport** [comment]
UAT - Fail 

inconsistent results depending on order of words and results omitted for not containing some words.

"Camera Bag" returns 2 results both bags
http://demo.lend-engine.com/products?search=camera+bag
"bag camera" returns three results, one bag, one camera and one lens
http://demo.lend-engine.com/products?search=bag+camera

"Petrol" returns one result and "Petrol Heart" returns a different one result
http://demo.lend-engine.com/products?search=petrol
http://demo.lend-engine.com/products?search=petrol+heart
http://demo.lend-engine.com/products?search=heart+petrol

**Comment by LESupport** [comment]
UAT Pass 
Search results look good including both words from keywords and title as expected on both members site and admin item search, adding more words increases the search parameters, worked not long have to be in the right order.

**Comment by andortamas** [comment]
Deployed
