### ISSUE TITLE
Wrong basket time when lending a kit

### ISSUE THREAD

**Issue by andortamas** [lend-engine/lend-engine-app#140]
### Issue 1

When creating a reservation for North campus (HQ) that opens at 0900 and closes at 1500 the model showed the correct time, but the reservation shows pickup from 0600 and return at 1200, it should say pickup at 0900 and return at 1500 as there is no change over time at North campus (HQ).

![128687764-d4232c7b-d848-40c8-81db-d76c146e1c5a](https://user-images.githubusercontent.com/1197217/128721282-7f688e0b-5d2f-4dfd-8018-cef176d75a11.png)

![128685048-70ab9b03-99f6-4200-9ee4-ccdfb06d2ff0](https://user-images.githubusercontent.com/1197217/128721506-aef21af6-fab2-471d-91c5-28bfbabb3494.png)

### Issue 2

When adding a second loan item to an existing reservation with a location with changeover the pickup time is displayed correctly in the modal, but the reservation for the second item change to 0800 instead of 0700

![128687856-e90d915e-a33f-4572-8ec6-70e350f4350c](https://user-images.githubusercontent.com/1197217/128722501-c0311d34-e795-4046-9b8c-7d315cc9a4b0.png)

![128686189-61ee0028-f996-4967-bbc4-ab0397dfc2d9](https://user-images.githubusercontent.com/1197217/128721549-c585419f-d62a-4f8e-ac59-a44c04fb14cb.png)

### Issue 3

Adding another item to an existing reservation with a location without a changeover time, the modal shows the correct dates and times, but the reservation jumps forward an hour which is outside of the opening hours.

![128688699-cda224a7-3b2f-4fdd-a09a-e69fd3467f24](https://user-images.githubusercontent.com/1197217/128721798-2fef88a4-92d5-403e-afb7-44f4af50e4c9.png)

![128688709-d4869572-ddfd-4243-9726-4bf89aa55265](https://user-images.githubusercontent.com/1197217/128721809-f14b1d58-4a03-419a-b3be-f75de46cc258.png)

**Comment by LESupport** [comment]
UAT - Pass
Created a number of loans for custom hours regular hours and all times for loans created were correct on the basket, reservation, loans email and admin screens.

**Comment by andortamas** [comment]
Deployed.

**Comment by LESupport** [comment]
UAT tests for the fixes relating to this found by a customer who does long term loans

UAT - PASS with #127 issue ​still outstanding

All aspects of long term loaning work as expected, short term and kits also worked as expected, emails sent look good.
