### ISSUE TITLE
Pagination and count on Members report page

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#141]
User reporting not being able to see all the members and another user reported the count on users when filtering is incorrect

**Comment by LESupport** [comment]
checked with the customer - speelotheek when listing all members, it only shows members from A-M they are on the starter package.

**Comment by LESupport** [comment]
the membership report http://demo.lend-engine.com/admin/report/report_memberships does not fuction correctly, it only shows some of the data and some on the starter package are saying they can only seem A-M and that the scount at the bottom does not match the members shown

**Comment by andortamas** [comment]
Deployed Jun 20 at 6:25 PM
