### ISSUE TITLE
Unable to add a loan item to existing loan with adjacent booking

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#148]
With same-day loaning we have had an issue when a loan is created with one item and then another loan item is added which has an adjacent booking it prevents the booking with an error that there is a booking for this period. Our changeover time is 10am and it looks like the second item is trying to be added at 9am.

The below image is of a second item being added http://demo.lend-engine.com/product/1035
to reservation 1146 http://demo.lend-engine.com/loan/1146
The error is:- "This item is reserved or on loan for your selected dates
"Item needs checking each month" (#1035) is reserved by Alan Dalgairns (ref 1145, 15 Sep 10:00 - 22 Sep 10:00)
Requested 22 Sep 09:00 - 29 Sep 09:00 (STARTS)"

The requested time was 10am to 10am which is the changeover time for North Campus (HQ)

![unable to loan due to adjacent booking](https://user-images.githubusercontent.com/76882506/134162337-022b0996-1495-4bd4-8d62-cc95e41fc950.png)
.

**Comment by LESupport** [comment]
UAT Pass

Testing loaning and extending with both locations with changeover and without for items and with adjacent loans

Notes:-
When you have a mix of locations with change over time and without, same day loans were still possible on an item is borrowed from a location that allows same day loans, even if there is an adjacent loan of the same item from a location that does not allow the same day loans.

New bug found for extending loans using a location with the changeover, the extension goes to the end of the day instead of the beginning and causes a potential clash with existing booking. https://github.com/lend-engine/lend-engine-app/issues/169

**Comment by andortamas** [comment]
Deployed
