### ISSUE TITLE
Request to complete two languages Slovak (update) and Ukrainian (new)

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#150]
Slovak has been updated to 100% and Ukrainian is a new language that will need to be added to the Language picker too.

Both have been checked and variables are good to go.
Ukrainian
https://localise.biz/lendengine/lendengine#!l=126508
Slovak
https://localise.biz/lendengine/lendengine#!l=57411

**Comment by LESupport** [comment]
UAT: Pass all changes work and language is selectable.

**Comment by andortamas** [comment]
Deployed
