### ISSUE TITLE
Edge case :- Converting an item from a loan item to a stock item then back to a loan item due to error fails.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#171]
There is a "change type" button when you edit the item which can be used to convert an item, when converting a stock item to a loan item there is an error 

"Item is on open loans. Please close all loans for this item first." 

It does not appear to be on any open loans. this can be recreated on item http://demo.lend-engine.com/admin/item/1036

![convert item error](https://user-images.githubusercontent.com/76882506/145041420-524d383c-9c75-4d25-8942-e099faa7b9e3.png)
.

**Comment by andortamas** [comment]
Deployed
