### ISSUE TITLE
Checkout failure due to "delivery" item already "reserved" Payment taken and not recoded

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#175]
Checkout failure causes deposit and loan costs to be taken and added as credit to the account, but deposit is also taken and not recorded in LE

Steps to recreate 
Enable Delivery in "Loan and Reservations"
Create a cost for Loan only.
Use an item that has a deposit
Reserve for delivery and checkout 
using another user to create another loan of a similar item with a deposit and reserve for delivery.
checkout that loan and an error similar to this will appear 
"We can't check out: "Shipping" (#1026) is reserved by Jane Doe (ref 1191, 31 Dec 07:00 - 22 Dec 15:35) Requested 28 Dec 10:00 - 28 Dec 16:17 (CONTAINS)"

At the bottom where payment info is you also get the error "There was a problem completing your previous payment.
We have charged your card and the amount has been added to your balance. If you would like this amount to be refunded, please get in touch."

Item will not be despatched, payment will be taken by stipe, no record of payment of the deposit in LE, users account will show pending loan with credit on account.

![failed to checkout due to delivery](https://user-images.githubusercontent.com/76882506/147586784-37e18ab2-4f01-48e6-9dcd-c886301278c2.png)

![failed to checkout due to delivery1](https://user-images.githubusercontent.com/76882506/147587179-d8608dc1-6fd4-4391-9a9c-b4606e071b4b.png)

![failed to checkout due to delivery2](https://user-images.githubusercontent.com/76882506/147587995-5ba72130-88f8-4c56-984a-7b6a2eca737c.png)

**Comment by andortamas** [comment]
Deployed
