### ISSUE TITLE
Unable to disable self-serve on membership types

### ISSUE THREAD

**Issue by dweggemans** [lend-engine/lend-engine-app#177]
I have 3 existing membership types with cost > 0 and self-serve set to Yes. Whenever I try to edit these membership types I get an error `Self serve memberships cannot have a price if you don't have Stripe configured. We have not saved your changes`. 

We have disabled registration on the member site and members should not be able to change their membership type themselves. However, I have no options to change this in the edit screen. I cannot change anything whatsoever because the membership types seem to be in an invalid state. 
My goal is to have self-serve disabled and maintaining the set price on the membership types. Admins should be able to signup new members, assign a membership and handle cash payments.

Please advice on how to proceed.

**Comment by LESupport** [comment]
Please email support@lend-engine.com for support on this.
