### ISSUE TITLE
Pending status not showing correctly in dashboard

### ISSUE THREAD

**Issue by YvetteKlinkenberg** [lend-engine/lend-engine-app#184]
The dashboard shows that there's 1 pending load, however, if I search for pending status (within a huge time period) no loans are pending. See attached screenshot
<img width="879" alt="LE_pending_bug_1" src="https://user-images.githubusercontent.com/17195572/155835497-05fff88f-aaec-43ef-8a02-ecf22b9048f0.PNG">

**Comment by andortamas** [comment]
The related bugfix in #188 deployed
