### ISSUE TITLE
Able to add a loan item to a loan that is already checked out

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#197]
When a loan is checked out by an admin and you then start the process of creating a loan for another user it is sometimes possible to add the item you are reserving to the last loan you checked out leaving it in a limbo state where you cant check the item back in or perform any action on that one item that was added to the already checked out loan.

It should never be possible to add an item to an already checked out loan, but it appears that it is possible and requires support to sort out each individual case.

**Comment by LESupport** [comment]
UAT complete, unable to add loans to loan types other than Active and pending.
![Uploading overdue.png…]()
![active loan](https://user-images.githubusercontent.com/76882506/173397263-1b2611b7-7031-4f4c-ab15-44fcf89fd2ac.png)

**Comment by andortamas** [comment]
Deployed
