### ISSUE TITLE
GDPR issue, able to see the name of someone who has an item booked without being admin or staff, also a standard user can see checkout prompts which are for admin/staff only.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#202]
When booking an item for a length over an existing booking you get the error that it's already reserved, this is usually anonymous for standard users, but it's currently showing the name of the person who has it booked.

Below screenshot from a standard user account.
![GDPR](https://user-images.githubusercontent.com/76882506/177131488-2fa697f2-54cb-46a2-90bf-3f9b221cfb80.png)

**Comment by LESupport** [comment]
Please include this issue too
A standard user can see the checkout prompts which are for Admin/Staff only, they cant act on them, but its confusing that they are there on a standard user account and should not be visible.

**Comment by LESupport** [comment]
UAT - Pass, multiple tests on loan creations and multiple baskets, tested self-checkout works OK too.

**Comment by andortamas** [comment]
Deployed
