### ISSUE TITLE
Flag user account with message and prevent borrowing until its cleared.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#208]
If there is an issue with a user account that needs to be flagged and dealt with on the return of the customer, enable the admin/staff to set a flag and add a message that needs to be cleared before that user's reservations can be checked out. This could be an extension to the notes area on the contacts page. If a flag is created, it should show who created it and who cleared it.

**Comment by andortamas** [comment]
Waiting the db migration ending...

**Comment by andortamas** [comment]
Deployed
