### ISSUE TITLE
Cancellation of subscription did not happen

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#215]
W had an account created on the 8th September, they subscribed to the plus plan on the 15th September and then cancelled on the 27th September, but the cancellation did not happen in Stripe and a further payment was taken.

Everything looks good in the admin panel, but the stripe subscription was still active. 
they were then charged on the 15th Oct 
tenant 3930
stripe customer ID (provided on whatapp)

**Comment by andortamas** [comment]
Reviewed the codebase but has not found any issues. Alan cancelled the payment manually.

Will keep our eye on next subscriptions and debug them.
