### ISSUE TITLE
CSV Exports are still not matching the data if you compare the report to the dashboard for one account 

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#216]
CSV Exports are still not matching the data if you compare the report to the dashboard for Overdue and On loan by a lot.

The customer is currently unable to report data correctly.

Tenant 579

See whatapp for report v screenshot

**Comment by LESupport** [comment]
UAT Pass, counters and report look good.

**Comment by andortamas** [comment]
Deployed
