### ISSUE TITLE
Repeating custom hours, span a period of days

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#220]
Some sites are always closed on specific days of the year, and a request to make custom hour repeat every year on the same day
Request to allow the custom period to span many days instead of one day at a time.

![custom hours](https://user-images.githubusercontent.com/76882506/201999283-fb22b8c5-a675-4881-83b7-69c326c4643b.png)

**Comment by andortamas** [comment]
Deployed
