### ISSUE TITLE
No price or length of borrow when browsing

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#224]
When an item is zero cost to borrow or membership gives a 100% reduction in fees, and you browse the items it no longer shows the cost or length of borrow below the item. 

i.e it should say "£0.00 for 7 days" instead it's blank.
![no price](https://user-images.githubusercontent.com/76882506/211538840-762d61aa-5f83-4053-9afe-5f594eab8f8e.png)

**Comment by andortamas** [comment]
Deployed
