### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to AppBundle\Entity\Payment::setPaymentMethod() must be an instance of AppBundle\Entity\PaymentMethod, null given, called in /app/src/AppBundle/Controller/Loan/LoanContro  URL

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#231]
https://rollbar.com/lend-engine-eu-plus/lend-engine-eu-plus/items/242/

**Comment by andortamas** [comment]
Tried repplicate the issue on local with the same data, but no luck. I've tried pass invalid and empty payment method ids, but the form catches this case and displays this on the form.

The all I could do at this stage to check the payment class to ensure it doesn't break the script.

**Comment by andortamas** [comment]
Deployed
