### ISSUE TITLE
PDOException: SQLSTATE[HY000] [1040] Too many connections

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#232]
https://rollbar.com/lend-engine-eu-plus/lend-engine-eu-plus/items/310/

**Comment by andortamas** [comment]
This issue has not happened in the last 9 days.

Checked the max connection setting in the MySQL and created an alarm to ring a bell before it reaches the max number of connections.

The current treshold is $max-10

**Comment by andortamas** [comment]
Continued on #237
