### ISSUE TITLE
RuntimeException: Unable to create the cache directory (/app/var/cache/prod/twig/e7).

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#233]
https://rollbar.com/lend-engine-eu/lend-engine-eu/items/857/occurrences/312038107702/

**Comment by andortamas** [comment]
This issue has not happened in the last 9 days.

Checked the max connection setting in the MySQL and created an alarm to ring a bell before it reaches the max number of connections.

The current treshold is $max-10

**Comment by andortamas** [comment]
Environment error. No fix required.
