### ISSUE TITLE
[lend-engine-eu] prod - New Error: #860 Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#234]
This was thrown at the time of registering the site, it also caused a small outage across the servers.

 [https://rollbar.com/lend-engine-eu/lend-engine-eu/items/860/occurrences/312674891930/

**Comment by andortamas** [comment]
This is a typical issue whilst the db is not deployed yet and somebody tries to open the portal which is still in creating status.
