### ISSUE TITLE
Pay membership at pickup on and allow account to go into debt.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#240]
Many people fail to move forward past the paywall of membership subscriptions due to not wanting to put their credit card information on the site. about 30-50% of the total signed up don't take a membership.

Add a feature that allows an optional "pay membership at pickup" and allows the account to go into debt by the amount of the subscription; this will then allow memberships to be taken at the site with the first reservation.

Must be switchable (off by default for backward compatibility)
Must ensure that the accounts can go into debt by the cost of the memberships. ("Credit limit"option on memberships)

**Comment by LESupport** [comment]
Pass tested both with and without functionality both work as expected. Deploy.

**Comment by andortamas** [comment]
Deployed.

**Comment by andortamas** [comment]
Reverted: https://app.rollbar.com/a/lend-engine-eu-plus/fix/item/lend-engine-eu-plus/336

**Comment by andortamas** [comment]
Fixed and deployed.
