### ISSUE TITLE
Overdue email sends a link button to open loan, but the URL is wrong

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#252]
The button "View this loan online" in the overdue email does not work. Here is the link to an overdue email where the link is below; you can see the URL is on there twice.

https://playablesg.lend-engine.complayablesg.lend-engine.com/access?t=63e1217ea3873&e=sherrysoon%40gmail.com&r=/loan/60

<img width="467" alt="image (1)" src="https://github.com/lend-engine/lend-engine-app/assets/76882506/c67ffa00-7529-4027-94dd-ab6bdf9696af">
<img width="386" alt="image" src="https://github.com/lend-engine/lend-engine-app/assets/76882506/a110b962-ed94-403a-8f98-fcff059f3dba">

**Comment by andortamas** [comment]
Deployed
