### ISSUE TITLE
Errors appearing with Stripe transactions not matching with LE

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#256]
A number of cases have been reported of credit being added and then the total in LE being wrong by 100x

I,E, someone adding credit and the total was £11.00 added and this is the amount recorded in Stripe, but LE showing only 11p
Another example is where a loan for £0.00 (zero cost) but a deposit of £40 would leave a residual in the LE account of 100x less ie £0.40p

Not able to replicate so getting more information 

I did notice 

If you add money, but use the return/enter key to complete the transition instead of the "add money" button it does not store the Stripe ID on the transaction.
![addmoney](https://github.com/lend-engine/lend-engine-app/assets/76882506/623a1210-623f-4851-b160-ef37e37aaff5)

There is no proforma for adding money i.e. 0.00 just a blank box field and you can use some alpha characters that give odd results such as the £ sign, which brings up the enter new card details box in a stripe transaction or a p i.e. 50p which will ad £50 to the account.

![add money2](https://github.com/lend-engine/lend-engine-app/assets/76882506/f1571503-37bb-46d2-9357-147eb393ed07)

**Comment by andortamas** [comment]
The issue has been found and fixed it. The problem happened when:
- Payment is sent and the card provider required the 3D secure
- Payment.js handled the 3D and sent the payment form, but with the wrong amount (not multiplied by 100 as expected)
- The payment form data has saved into the payment table with the wrong amount
- If the script executed correctly, the add-credit action overwrote the payment amount with the correct amount
- If the script stopped, the pending payment (with the wrong amount) has left as is

**Comment by LESupport** [comment]
Any ideas on how to test this and stop the script for the pending transaction to have the incorrect amount transacted?

**Comment by andortamas** [comment]
Honestly, it must break the payment processing from the codebase, but it's not possible on the staging.

I think the best way to test the payment is to ensure this fix has not broken anything on the payments (including the 3D secure card payments as well).

**Comment by LESupport** [comment]
Pass - I've tested all types of payment, including reservation payments, using both 3D secure and normal without any issues.

**Comment by andortamas** [comment]
Deployed.
