### ISSUE TITLE
[GO] Enhancement 9 browsing as - more visible

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#261]
As an Admin\Staff member, make the “browsing as” feature more visible and allow a cancel
button to switch this off.

Original request data for visibility
9. Highlight the browsing as part. A lot of volunteers find it really difficult to understand who they are
working with at the moment.

**Comment by andortamas** [comment]
It's on the beta. If you can't see the yellow highlighted area, please press Ctrl + F5 in your browser to reload css files.
![Screenshot 2023-10-02 at 17 58 22](https://github.com/lend-engine/lend-engine-app/assets/1197217/da763716-8617-4455-ae6c-6530d30bb9b1)

**Comment by LESupport** [comment]
Pass - works like it was described.

**Comment by andortamas** [comment]
Deployed.
