### ISSUE TITLE
[GO] Enhancement 13 loan reminder emails incorrect.

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#263]
As a user, I want the reminder email to show which items on a loan have already been
returned and which ones are outstanding.

As a Staff/Admin I need to be able to see in the loan list which items have been returned and which items are outstanding without going into the loan to see the specific statuses/

Also noted in (BUG) #170  (and #203  and #217 )

Original request data for visibility
13. If a member borrows several items in one loan and then return some of them, but not all. A reminder for all items is sent to the member. About every 10:th of the e-mails that we get are from members explaining that they have already returned their items.
Wish: For the bug to be fixed.

**Comment by andortamas** [comment]
Fixed the email reminder loan rows and also found a html template issue which rendered the table cells and rows incorrectly:

Before the fix:
![email-rendering-issue](https://github.com/lend-engine/lend-engine-app/assets/1197217/c270bfac-d092-4d1c-a5ac-9bf8e75110eb)

After the fix:
![email-rendering-fix](https://github.com/lend-engine/lend-engine-app/assets/1197217/9ad441ba-c1ce-4673-9ef1-40ff69d52e5a)

**Comment by andortamas** [comment]
Deployed

**Comment by andortamas** [comment]
Bug has been reported that the email reminder contained many other items which were not in the loan.

**Comment by LESupport** [comment]
Cant test as the demo has no email service. please deploy.

**Comment by andortamas** [comment]
Deployed
