### ISSUE TITLE
[FR] Enhancement 15 TBC reservation fees - only for the selected clients

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#264]
As An Admin I want reservation fees to be charged only at some locations(not sure if this is sites or locations yet)

**Comment by chris-b-tanner** [comment]
This could be implemented as a checkbox per site, ie "charge reservation fees". 
Default would be "yes" for existing customers. With it on "no", any reservation fee set at the organisation level is waived.
Available on all pay plans for simplicity.

**Comment by LESupport** [comment]
After discussing with Yrsa it would appear they want a flag on the user profile to decide if they need to pay a deposit or not, The person would always be at the satellite sites and never go to the main library. 

"As a user or an admin/staff member browsing as another user, I want to be able to reserve things that have a reservation fee, without being shown or asked to pay the reservation fee when reserving items. A flag on the user profile will decide if any reservation fees are paid or not.

The person would always be at the satellite sites and never go to the main library. 

Text for completion
When it comes to "15" what we mean is the following: for example,
once a month we go to a remote place (this year a library in another
part of Gothenburg) where we do a playful activity and allow members to
pick up reserved toys. These members usually do not come to our home toy
library, but do all their lending through reservations to the remote
place (checking in their last loan, picking up a new reserved bay of
toys). Therefor we would like to skip the reservation fee for them.
Another example is that we have a few members living far away coming to
us once a month picking up a reservation, for these people we would also
like to skip the reservation fee. So we would like to be able to adjust
the reservation fee for specific members (a checkbox "no reservation fee
for this member") and/or for specific memberships (so that all members
of a specific membership could be removed from reservation fees). Did
this make it clearer? :)

**Comment by andortamas** [comment]
Implemented the charge reservation fee flag.

Please note: stock items and services are not affected.

**Comment by LESupport** [comment]
UAT Pass - Works as expected

**Comment by andortamas** [comment]
Deployed
