### ISSUE TITLE
Self Serve Registration where user needs to pay a fee fails with "oops" screen if stripe is not connected

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#80]
Steps to reproduce.
Create self serve Membership with a fee 
Create a new user
Select payment method (cash £5)
Oops screen appears but does subscribe the user to the membership.

Screenshot inc console view https://photos.app.goo.gl/djXshtHQcBihBcpU6

Error noticed by Yvette @ bestuur@speelotheekwageningen.nl

**Comment by LESupport** [comment]
Also need to inform sophia.strilets@outlook.com when this is fixed

**Comment by chris-b-tanner** [comment]
@andortamas : please ensure that if a user has not got a Stripe API key in their settings, they cannot set a self serve membership type with a fee. Self serve fees can only be paid via the Stripe integration.

When saving the membership type:
If StripeFeeInSettings is not set and MembershipTypeFee != 0
Then Add error flash message and return user to MembershipType settings list.
