### ISSUE TITLE
No default location set in Site causes Oops message when adding a new item

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#82]
Steps to reproduce 
1. Make default check-in location is inactive (Active? unchecked) and Item available at this location was unchecked for this test.
2. Open the "sites and opening hours" section and click edit, you will notice the default checking location is missing, you can now hit save and it saves a blank check-in location.

Now when you click to add an item you will get the oops screen.

Some validation needs doing here, possibly prevent the "default check-in location" for a site from being changed to inactive without selecting an alternative?

**Comment by chris-b-tanner** [comment]
@andortamas Can you ensure that a user cannot deactivate a location if it is set as the default check in location for a site? 
Probably easiest to override the user's choice after they have submitted the form (and let them know via a flash error), rather than making any changes to the form for the location edit modal.

**Comment by chris-b-tanner** [comment]
@LESupport We can't replicate this - can you double check?

**Comment by LESupport** [comment]
Yes, I can repeat this, here are some screenshots, let me know if you want a video
![site inactive](https://user-images.githubusercontent.com/76882506/109013400-075db900-76ab-11eb-92ff-9e9775f8290c.png)
![edit main site](https://user-images.githubusercontent.com/76882506/109013407-0af14000-76ab-11eb-9593-5c52f3ea2ee1.png)
![add loan item](https://user-images.githubusercontent.com/76882506/109013425-0f1d5d80-76ab-11eb-9fad-550711c73132.png)
![oops](https://user-images.githubusercontent.com/76882506/109013437-12b0e480-76ab-11eb-8c50-1a67d1d5951f.png)

**Comment by LESupport** [comment]
Released
