### ISSUE TITLE
Map on Dashboard does not show all members

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#89]
The map seems to get to a maximum number and stop putting dots on the map. If its to show all members it does not function correctly. I'll look into this more and see if I can pinpoint where it goes wrong.

**Comment by LESupport** [comment]
I have managed to complete a full address update of all my members, I changed the County from East Yorks or East Yorkshire to "East Riding of Yorkshire" and all the markers on the map appeared. It would be good to know what data is required and what it does if the info is slightly incorrect, we can add this to the manual.

**Comment by YvetteKlinkenberg** [comment]
I've checked the completeness of the membership details and for members shown and those not shown I haven't found differences. Although I didn't fill in the membership number, this didn't made any differences when adding it to the members details. County, City and Country are set with similar values (for as far as I can see) but some are shown on the map, and most are not shown. I get the feeling that the map doesn't update; that only old members are shown and new members aren't added, but that's more of a feeling than an substantiated argument

**Comment by YvetteKlinkenberg** [comment]
This map is disappeared from the dashboard?!?

**Comment by andortamas** [comment]
Deployed
