### ISSUE TITLE
Cannot hide section once a category has been added

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#90]
Steps to recreate
Add new section using Settings. Item Section.
Notice it does not appear on the member's site even if show on website is "Yes"

Add a category and the section appears, but you cant hide the section by setting "Show on website" to No.
<img width="1440" alt="image (1)" src="https://user-images.githubusercontent.com/76882506/108358398-97e95480-71e6-11eb-9ac6-6281a636c9f7.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76882506/108358405-99b31800-71e6-11eb-9ef6-e5d219422087.png">

**Comment by chris-b-tanner** [comment]
Won't fix this - if you want to hide a section, move the categories elsewhere then hide it.

**Comment by LESupport** [comment]
I've told Marc and give him a solution. I'll close this one
