### ISSUE TITLE
No delivery cost on loan information

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#92]
The cost of delivery is not displayed on the loan information (receipt) email sent to customers, here is an example from Marc at Grobikes.com

![no delivery change mentioned](https://user-images.githubusercontent.com/76882506/108877519-37e41b00-75f7-11eb-8165-261ba2207cfa.png)

**Comment by chris-b-tanner** [comment]
Will close as "won't fix" so we can focus on other things for now.
