### ISSUE TITLE
Incorrect hours being sent in emails

### ISSUE THREAD

**Issue by chris-b-tanner** [lend-engine/lend-engine-app#96]
There are reports of emails (loan reminders, confirmations etc) showing the wrong time for libraries who are not in UTC timezone. See notes and comments for examples.

**Comment by chris-b-tanner** [comment]
For https://utbud.leksaksbiblioteket.se/
In this e-mail. In the e-mail confirming that the members have a
reservation to pick up it says that we open at 1pm,(see screenshot) but
we open at 2 pm. This seems to be automatically generated. Could it be
something with the timezones?
![Screenshot 2021-03-17 at 14 22 11](https://user-images.githubusercontent.com/30432399/111551289-ccb1e280-8777-11eb-963c-b1427ce1b059.png)

**Comment by chris-b-tanner** [comment]
We have automatic reminder emails set up in lend engine. This member received reminder emails for both pick up and due dates that were at the incorrect time - 5pm. We are only open between 6-7pm. 
Her loan is correctly scheduled during opening hours, i.e. starting at 6pm.
We haven't heard of this happening to other members, but any idea why her reminders are for the wrong time? This unfortunately left the member waiting around for a while when she picked up the item.

![circle](https://user-images.githubusercontent.com/30432399/111551721-bb1d0a80-8778-11eb-889b-81e72936702d.png)
<img width="838" alt="Screenshot 2021-03-17 at 23 30 37" src="https://user-images.githubusercontent.com/30432399/111551749-ce2fda80-8778-11eb-890c-8226c16d94e6.png">
<img width="1026" alt="Screenshot 2021-03-17 at 23 32 07" src="https://user-images.githubusercontent.com/30432399/111551858-118a4900-8779-11eb-9ab5-da551f8521b5.png">

The org_timezone setting for circlesentrelund is Europe/Stockholm

**Comment by chris-b-tanner** [comment]
Both reported accounts are in Sweden (may or may not be relevant), but their DST starts 28th March. I believe there is an open issue where one of the start or end dates renders wrong if the loan straddles the daylight saving change, but that shouldn't have affected loan 1012 above.

**Comment by YvetteKlinkenberg** [comment]
We had members visiting 1 hour early as well last Saturday (set time zone GMT+1, Amsterdam, site Speel-o-theek Wageningen). This may be due to the same issue with the opening time in the loan reminder email.

**Comment by andortamas** [comment]
I've replicated the issue and fixed this in the following services:
- Loan reminder emails
- Reservation reminder emails
- Overdue loan emails

**Comment by andortamas** [comment]
Fixed the issue by passing the time in string format to the email template.
